name: K Soh
short_title: K Soh | SE & DS
title: K Soh | Software Engineer & Data Scientist

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wksoh.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: "img/emojis/technologist.png"
email: annoying.spammer83295@gmail.com
cover: "https://wksoh.com/img/featured/og.jpg"

blog_enabled: false
description: >- # this means to ignore newlines until "email:". Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  I'm K Soh, a design minded software engineer & data scientist focused on developing user-friendly apps & products.
keywords: "ksoh, web, web development, ai, datascience, javascript, singapore, malaysia, flutter, apps, mobile apps"
social:
  - title: email
    url: mailto:annoying.spammer83295@gmail.com
  - title: github
    url: https://github.com/notaunty
  - title: linkedin
    url: https://www.linkedin.com

source: src
destination: ./_site

sass:
  style: compressed
  sourcemap: never
  sass_dir: _sass


collections_dir: collections

collections:
  blog:
    output: true
    permalink: /:collection/:title


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package.json
#   - build


# Build settings
# theme: minima
# plugins:
#   - jekyll-minifier
#   - jekyll-feed
#   - jekyll-sitemap

